PAV/urls.py
from django.contrib import admin
from django.urls import path, include
from f_proc import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('files/', include("f_proc.urls")),
    path('user/', include("user.urls")),
    path('', include("show.urls")),
]

# 配置自定义的 404 处理视图
handler404 = 'f_proc.views.custom_404_view'

f_proc/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("random/", views.random_all, name="random"),
    path("myrandom/", views.random_filter, name="random_filter"),
    path("upload/", views.upload, name="upload"),
    path("upload_dir/", views.upload_dir, name="upload_dir"),
    path("upload_hls/", views.save_hls_data, name="save_hls_data"),
    path("list/", views.file_list, name="file_list"),
    path("recycleBin/", views.recycleBin, name="recycleBin"),
    path("data/<str:md5>/", views.get_file_data, name="get_file_data"),
    path("upload_files/", views.save_file_data, name="save_file_data"),
    path('ct/manage/', views.manage_appertain, name='manage_appertain'),
    path('ct/manage/<int:pk>/', views.manage_appertain, name='manage_appertain'),
    path("filter/", views.file_search, name="file_search"),
    path("v2hls/", views.v2hls, name="v2hls"),
    path("v2hls/<str:md5>/", views.vFile_to_HLS, name="vFile_to_HLS"),
    path('v2hls/status/<str:md5>/', views.v2hls_task_status_view, name='v2hls_task_status'),
    path("check/<str:md5>/", views.check_and_delete_file_chunks, name="check_and_delete"),
    path("delete/", views.delete, name="delete"),
    path("delete/<str:md5>/", views.delete_file, name="delete_file"),
    path("status/disable/<str:md5>/", views.set_file_status_disable, name="set_file_status_disable"),
    path("status/enable/<str:md5>/", views.set_file_status_enable, name="set_file_status_enable"),
    path("update/<str:md5>/", views.update_file_info, name="update_file_info"),
]

f_proc/models.py
import uuid
from decimal import Decimal
from django.db import models


class FileInfo(models.Model):
    name = models.TextField()
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    md5 = models.CharField(max_length=32)
    size = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal('0.00'))
    type = models.CharField(max_length=16, default="unknown")
    mime = models.CharField(max_length=128, default="unknown")
    wh = models.JSONField(null=True, blank=True)
    level = models.CharField(max_length=16, default="General")
    data = models.JSONField(null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    delete_time = models.DateTimeField(null=True, blank=True)
    author = models.CharField(max_length=64, null=True, blank=True)
    album = models.TextField(null=True, blank=True)
    subject = models.TextField(null=True, blank=True)
    hls_addr = models.CharField(max_length=128,null=True, blank=True)
    thumbnail_addr = models.CharField(max_length=128, null=True, blank=True)
    source_addr = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=16, default="enable")
    remark = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'file_info'

class FileAppertain(models.Model):
    FLAG_CHOICES = [
        ("C", "Catalogue"),
        ("T", "Tag"),
    ]
    name = models.CharField(max_length=128, unique=True)
    flag = models.CharField(max_length=1, choices=FLAG_CHOICES)
    parent = models.IntegerField(default=0)  # 默认 parent 为 0

    class Meta:
        db_table = 'file_appertain'

class FileRelationship(models.Model):
    file_info = models.ForeignKey(FileInfo, on_delete=models.CASCADE, related_name='relationships')
    file_appertain = models.ForeignKey(FileAppertain, on_delete=models.CASCADE, related_name='relationships')

    class Meta:
        db_table = 'file_relationship'

f_proc/forms.py
from django import forms
from .models import FileAppertain, FileInfo

# 单文件上传测试所创
class UploadFileForm(forms.Form):
    file = forms.FileField()

# 多文件上传测试所创
class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result

class FileFieldForm(forms.Form):
    album = forms.CharField(required=False)
    subject = forms.CharField(required=False)
    categorySelect = forms.CharField(required=False)
    levelSelect = forms.CharField(required=False)
    inputTags = forms.CharField(required=False)
    file_field = MultipleFileField()

class SearchFileForm(forms.Form):
    query = forms.CharField()
    
class FileAppertainForm(forms.ModelForm):
    parent = forms.ModelChoiceField(
        queryset=FileAppertain.objects.all(),
        required=False,
        empty_label="无父分类",
        label="父分类",
    )

    class Meta:
        model = FileAppertain
        fields = ['name', 'flag', 'parent']
        labels = {
            'name': '名称',
            'flag': '类型',
            'parent': '父分类',
        }
        widgets = {
            'flag': forms.Select(choices=FileAppertain.FLAG_CHOICES),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].label_from_instance = lambda obj: f"{obj.name} ({obj.flag})"

    def clean_parent(self):
        parent = self.cleaned_data.get('parent')
        return parent.id if parent else 0
    
class FileInfoForm(forms.ModelForm):
    class Meta:
        model = FileInfo
        fields = ['name', 'album', 'subject']

f_proc/views.py
import os
import re
import uuid
import json
import shutil
import logging
import threading
from datetime import datetime
from django.db import transaction
from django.utils import timezone
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.core.paginator import Paginator
from .forms import FileInfoForm, FileAppertainForm
from .models import FileInfo, FileRelationship, FileAppertain
from .fproc import get_f_ext, get_md5, reset_auto_increment, generate_encryption_key, convert_to_encrypted_hls, get_image_wh, replace_in_list

# 设置日志
logger = logging.getLogger("f_proc")
# 用于存储任务状态的字典
v2hls_task_status = {}
# 用于保护 task_status 字典的锁
v2hls_task_status_lock = threading.Lock()

# 定义404页面
def custom_404_view(request, exception):
    return render(request, 'f_proc/404.html', status=404)

# 上传多文件页面
def upload_dir(request):
    try:
        categories = FileAppertain.objects.filter(flag="C")
    except Exception as e:
        logger.error(f"获取分类时出错: {str(e)}")
        categories = []  # 错误情况下使用空列表
    return render(request, 'f_proc/upload_dir.html', {'categories': categories})

# 上传单文件页面
def upload(request):
    try:
        categories = FileAppertain.objects.filter(flag="C")
    except Exception as e:
        logger.error(f"获取分类时出错: {str(e)}")
        categories = []  # 错误情况下使用空列表
    return render(request, 'f_proc/upload.html', {'categories': categories})

# 文件清单页面
def file_list(request):
    try:
        file_info_list = FileInfo.objects.all().order_by('-created_time')
    except Exception as e:
        logger.error(f"获取文件列表时出错: {str(e)}")
        file_info_list = FileInfo.objects.none()  # 遇到错误时返回空查询集
    
    paginator = Paginator(file_info_list, 20)  # 每页显示15个文件
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'f_proc/list.html', {'page_obj': page_obj})

# 建立文件与分类/标签关系
def create_file_relationship(file_info, appertain_id=None, appertain_name=None, flag='T', parent=0):
    if appertain_id:
        file_appertain = FileAppertain.objects.get(id=appertain_id)
    elif appertain_name:
        file_appertain, created = FileAppertain.objects.get_or_create(name=appertain_name, flag=flag, parent=parent)
    else:
        return  # 如果没有传入有效的 ID 或名称，则不进行操作

    # 创建 FileRelationship
    FileRelationship.objects.create(file_info=file_info, file_appertain=file_appertain)

# 上传文件，并将数据写入数据库
def handle_uploaded_file(file, file_info):
    # 定义文件分块的大小为1M
    chunk_size = 1024 * 1024  # 1MB
    # 定义文件分块后，每个块数据的位置被保存在该数组中
    file_info.data = []
    # 定义文件块的保存路径
    baseDir = os.path.join('media', timezone.now().strftime('%Y-%m-%d'), file_info.md5)
    
    # 开始处理上传文件：将文件进行分块存储
    try:
        # 创建文件块保存目录
        os.makedirs(baseDir, exist_ok=True)
        # 写入文件块数据
        with file.open('rb') as f:
            while True:
                chunk_data = f.read(chunk_size)
                if not chunk_data:
                    break
                chunk_uuid = str(uuid.uuid4())
                chunk_path = os.path.join(baseDir, chunk_uuid)
                with open(chunk_path, 'wb') as chunk_file:
                    chunk_file.write(chunk_data)
                file_info.data.append(chunk_path)
        
        file_info.data = json.dumps(file_info.data)
        file_info.source_addr = baseDir
        # 重置数据库，保证数据ID顺序自增长
        reset_auto_increment()
        # 将数据保存入数据库
        file_info.save()
        
    except Exception as e:
        logger.error(f"保存文件 {file.name} 时出错: {str(e)}")
        
        # 清理已创建的文件和目录
        for path in json.loads(file_info.data):
            if os.path.exists(path):
                os.remove(path)
        if os.path.exists(baseDir):
            shutil.rmtree(baseDir)
        raise

# 处理上传文件
def save_file_data(request):
    # 如果上传文件，则保存文件
    if request.method == 'POST':
        files = request.FILES.getlist('file_field')
        tags = request.POST.get('manyTags', '').split('/')
        album = request.POST.get('album')
        subject = request.POST.get('subject')
        category_id = request.POST.get('categorySelect')
        level = request.POST.get('levelSelect')
        img_wh = {"w":None, "h":None}
        
        # 定义上传文件的结果
        upload_result = {"successful":[], 
                         "exist":[], 
                         "failed":[]
                         }
        
        for file in files:
            # 获取文件基础信息
            file_md5 = get_md5(file)
            exist_file = FileInfo.objects.filter(md5=file_md5).first()
            # 判断文件是否已经存在
            if exist_file:
                upload_result['exist'].append({'name': file.name, 'md5': file_md5})
                logger.error(f"文件：\"{file.name}\"已存在，请检查！")
                continue
            # 如果上传文件为图片，则获取其宽度与高度
            try:
                if file.content_type.startswith('image'):
                    img_wh['w'], img_wh['h'] = get_image_wh(file)
            except (IOError, ValueError) as e:
                # 捕获与文件操作相关的异常
                logger.error(f"文件：\"{file.name}：{file_md5}\"读取错误或图片格式不正确: {e}")
            except Exception as e:
                # 捕获其他未知错误
                logger.error(f"读取文件：\"{file.name}：{file_md5}\"时，遇到错误: {e}")
            
            # 文件基础信息
            file_info = FileInfo(
                name=file.name,
                mime=file.content_type,
                wh=img_wh,
                size=file.size,
                type=get_f_ext(file)['file_extension'],
                album=album,
                subject=subject,
                level=level,
                md5=file_md5,
            )
            
            # 开始上传文件
            try:
                # 开始处理上传文件
                handle_uploaded_file(file, file_info)

                for tag in tags:
                    tag = tag.strip()
                    if tag:
                        create_file_relationship(file_info, appertain_name=tag)

                if category_id:
                    create_file_relationship(file_info, appertain_id=category_id)

                upload_result['successful'].append({'name': file.name, 'md5': file_md5})
            except Exception as e:
                upload_result['failed'].append({'name': file.name, 'md5': file_md5})
                logger.error(f"上传文件 {file.name} 时出错: {str(e)}")
                if file_info.id:
                    file_info.delete()
        
        return JsonResponse(upload_result)
    # 如果为访问上传页面，则将分类数据传给页面
    categories = FileAppertain.objects.filter(flag="C")
    return render(request, 'f_proc/upload.html', {'categories': categories})

# 管理分类标签页面
def manage_appertain(request, pk=None):
    appertain = get_object_or_404(FileAppertain, pk=pk) if pk else None
    response_data = {}
    
    if request.method == "POST":
        form = FileAppertainForm(request.POST, instance=appertain)
        name = form.data.get('name')
        flag = form.data.get('flag')
        
        if "add" in request.POST:
            if FileAppertain.objects.filter(name=name, flag=flag).exists():
                response_data['status'] = 'error'
                response_data['message'] = '分类名或标签名已存在！'
            elif form.is_valid():
                form.save()
                response_data['status'] = 'success'
                response_data['message'] = '保存成功！'
            else:
                response_data['status'] = 'error'
                response_data['message'] = '保存失败！'
                
        elif "update" in request.POST:
            if FileAppertain.objects.filter(name=name).exclude(pk=pk).exists():
                response_data['status'] = 'error'
                response_data['message'] = '分类名或标签名已存在！'
            elif form.is_valid():
                form.save()
                response_data['status'] = 'success'
                response_data['message'] = '更新成功！'
            else:
                response_data['status'] = 'error'
                response_data['message'] = '更新失败！'
                
        elif "delete" in request.POST and appertain:
            try:
                appertain.delete()
                response_data['status'] = 'success'
                response_data['message'] = '删除成功！'
            except Exception as e:
                response_data['status'] = 'error'
                response_data['message'] = f'删除失败：{str(e)}'
        
        return JsonResponse(response_data)

    else:
        form = FileAppertainForm(instance=appertain)

    appertains = FileAppertain.objects.filter(flag="C")
    return render(request, 'f_proc/ct.html', {
        'form': form,
        'appertains': appertains,
        'current_appertain': appertain
    })

# 获取文件数据，用以展示与下载
def get_file_data(request, md5):
    try:
        file_obj = FileInfo.objects.get(md5=md5)
        file_obj.data = json.loads(file_obj.data)
        return JsonResponse({'fileName':file_obj.name, 'fileDatas': file_obj.data, 'fileType':file_obj.type, 'wh':file_obj.wh, 'fileSize':file_obj.size, 'hlsAddr':file_obj.hls_addr})
    except FileInfo.DoesNotExist:
        return JsonResponse({'error': '文件未找到'}, status=404)
    except Exception as e:
        logger.error(f"获取文件数据时出错: {str(e)}")
        return JsonResponse({'error': '服务器错误'}, status=500)

# 查询文件
def file_search(request):
    try:
        data = request.GET.get('searchFiles', '')
        
        files = FileInfo.objects.all().order_by('-created_time')
        
        if data:
            files = files.filter(Q(name__icontains=data) | Q(md5__icontains=data) | Q(album__icontains=data) | Q(subject=data))

        paginator = Paginator(files, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        tags = FileAppertain.objects.all()
        return render(request, 'f_proc/filter.html', {'page_obj': page_obj, 'tags': tags})
    except Exception as e:
        logger.error(f"文件搜索失败: {str(e)}")

f_proc/templates/f_proc/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title></title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'f_proc/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'f_proc/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'f_proc/css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'f_proc/css/wallhaven-min.css' %}" />
</head>
<body>
    <header>
        {% block header %}
        <!-- Default header content -->
        {% endblock %}
    </header>

    <main class="main-container">
        {% block content %}
        <!-- Default content -->
        {% endblock %}
    </main>

    <footer>
        {% block footer %}
        <!-- Default footer content -->
        {% endblock %}
    </footer>

    <!-- JavaScript files -->
    <script src="{% static 'f_proc/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'f_proc/js/hls.js' %}"></script>
    <script src="{% static 'f_proc/js/all.js' %}"></script>
    {% block extra_js %}
    <!-- Additional JavaScript code can be included here -->
    {% endblock %}
</body>
</html>

f_proc/templates/f_proc/base_ct.html
<div class="container mt-5 cc-ct-container">
  <!-- 分类管理标题和新增分类按钮并排 -->
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h3 class="cc-font-ct-h3">当前分类</h3>
    <button
      id="addCategory"
      type="button"
      class="btn btn-success btn-lg"
      data-bs-toggle="modal"
      data-bs-target="#addCategoryModal"
    >
      新增分类
    </button>
  </div>

  <!-- 分类列表 -->
  <ul class="list-group mb-4">
    {% for appertain in appertains %}
    <li
      class="list-group-item d-flex justify-content-between align-items-center cc-ct-li-bk rounded-2"
    >
      <span>{{ appertain.id }}、 {{ appertain.name }} - {{ appertain.get_flag_display }}</span>
      <div>
        <button
          class="btn btn-sm btn-warning"
          onclick="editAppertain({{ appertain.id }}, '{{ appertain.name }}', '{{ appertain.flag }}', '{{ appertain.parent.id }}')"
        >
          编辑
        </button>

        <form
          method="post"
          class="d-inline-block"
          style="margin-left: 10px"
          action="{% url 'manage_appertain' appertain.id %}"
        >
          {% csrf_token %}
          <button type="submit" name="delete" class="btn btn-sm btn-danger">
            删除
          </button>
        </form>
      </div>
    </li>
    {% endfor %}
  </ul>

  <!-- 模态窗口，用于新增和编辑分类 -->
  <div
    class="modal fade"
    id="addCategoryModal"
    tabindex="-1"
    aria-labelledby="addCategoryModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <form method="post" id="appertainForm" class="cc-ct-modal-form">
          {% csrf_token %}
          <div class="modal-header">
            <h5 class="modal-title" id="addCategoryModalLabel">新增分类</h5>
          </div>
          <div class="modal-body">
            <div class="mb-3">
              <label for="id_name" class="form-label">名称</label>
              <input
                type="text"
                class="form-control"
                id="id_name"
                name="name"
                required
              />
            </div>
            <div class="mb-3">
              <label for="id_flag" class="form-label">标志</label>
              <select class="form-select" id="id_flag" name="flag" required>
                <!-- 这里添加标志选项 -->
                {% for choice in form.fields.flag.widget.choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="mb-3">
              <label for="id_parent" class="form-label">父分类</label>
              <select class="form-select" id="id_parent" name="parent">
                <option value="">无父分类</option>
                <!-- 这里添加父分类选项 -->
                {% for appertain in appertains %}
                <option value="{{ appertain.id }}">{{ appertain.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              取消
            </button>
            <button
              type="submit"
              name="add"
              class="btn btn-primary"
              id="addBtn"
            >
              保存
            </button>
            <button
              type="submit"
              name="update"
              class="btn btn-primary"
              id="updateBtn"
              style="display: none"
            >
              更新
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  // 追踪哪个按钮被点击
  let clickedButton = null;

  document.querySelectorAll("button[type=submit]").forEach((button) => {
    button.addEventListener("click", function () {
      clickedButton = this; // 记录点击的按钮
    });
  });

  // 拦截表单提交事件
  document.querySelectorAll("form").forEach((form) => {
    form.addEventListener("submit", function (event) {
      event.preventDefault(); // 阻止表单默认提交
      const form = this;
      const formData = new FormData(form); // 获取表单数据
      // 获取点击的按钮 name 属性，判断是 add 还是 update
      if (clickedButton) {
        formData.append(clickedButton.name, clickedButton.value);
      }

      const url = form.action;

      // 发送异步请求
      fetch(url, {
        method: "POST",
        body: formData,
      })
        .then((response) => response.json()) // 假设后端返回 JSON 数据
        .then((data) => {
          // 根据返回的 JSON 数据进行相应的处理
          if (data.status === "success") {
            // 成功处理逻辑，比如弹出成功提示框
            alert(data.message);
            // 重新加载页面以刷新分类列表
            location.reload();
          } else if (data.status === "error") {
            // 失败处理逻辑，比如弹出错误提示框
            alert(data.message);
          }
        })
        .catch((error) => {
          console.error("提交失败:", error);
          alert("提交失败，请检查网络或联系管理员。");
        });
    });
  });

  //当点击分类时，调用该方法
  function editAppertain(id, name, flag, parentId) {
    document.getElementById("addCategoryModalLabel").textContent = "编辑分类";
    document.getElementById("id_name").value = name;
    document.getElementById("id_flag").value = flag;

    const parentField = document.getElementById("id_parent");
    parentField.value = parentId || "";

    document.getElementById("addBtn").style.display = "none";
    document.getElementById("updateBtn").style.display = "inline-block";

    const form = document.getElementById("appertainForm");
    form.action = `{% url 'manage_appertain' %}${id}/`;

    const modal = new bootstrap.Modal(
      document.getElementById("addCategoryModal")
    );
    modal.show();
  }
  //监听当弹窗隐藏时，将弹窗元素重置
  document
    .getElementById("addCategoryModal")
    .addEventListener("hidden.bs.modal", function () {
      document.getElementById("appertainForm").reset();
      document.getElementById("addCategoryModalLabel").textContent = "新增分类";
      document.getElementById("addBtn").style.display = "inline-block";
      document.getElementById("updateBtn").style.display = "none";

      const form = document.getElementById("appertainForm");
      form.action = `{% url 'manage_appertain' %}`;
    });
</script>

f_proc/templates/f_proc/base_delete.html
<div id="v2hls" class="container mt-4">
  <div class="row justify-content-center v2hls">
    <div class="col-md-6">
      <form id="md5-form" method="get" class="input-group">
        <input
          type="text"
          id="md5-input"
          name="q"
          class="form-control rounded"
          placeholder="Delete file..."
          aria-label="Search"
        />
        <button class="btn btn-secondary rounded-3 ms-2" type="submit">
          Delete
        </button>
      </form>
      <div id="message" class="mt-4"></div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const form = document.getElementById("md5-form");
    const input = document.getElementById("md5-input");
    const messageDiv = document.getElementById("message");

    form.addEventListener("submit", async function (event) {
      event.preventDefault(); // 防止表单默认提交

      const md5Value = input.value.trim();

      if (!isValidMD5(md5Value)) {
        showMessage("请输入有效的 MD5 值。", "text-danger");
        return;
      }

      try {
        const response = await fetch(
          `http://127.0.0.1:8888/files/delete/${md5Value}`
        );

        if (!response.ok) {
          throw new Error("网络响应出错，请检查......");
        }

        const data = await response.json();
        showMessage(`${data.status}`, `${data.content}`);
      } catch (error) {
        showMessage("请求失败，请稍后再试。", "text-danger mt-3");
      }
    });

    function isValidMD5(value) {
      const md5Regex = /^[a-fA-F0-9]{32}$/;
      return md5Regex.test(value);
    }

    function showMessage(rStatus, rContent) {
      // 更新消息内容
      messageDiv.textContent = rContent;
      if (rStatus === "Successful") {
        messageDiv.className = "text-success mt-3";
      } else {
        messageDiv.className = "text-danger mt-3"; // 假设其他状态使用 text-danger
      }
    }
  });
</script>

f_proc/templates/f_proc/base_v2hls.html
<div id="v2hls" class="container mt-4">
  <div class="row justify-content-center v2hls">
    <div class="col-md-6">
      <form id="md5-form" method="get" class="input-group">
        <input
          type="text"
          id="md5-input"
          name="q"
          class="form-control rounded"
          placeholder="视频文件转换..."
          aria-label="Search"
        />
        <button class="btn btn-secondary rounded-3 v2hls-btn" type="submit">
          开始转换
        </button>
      </form>
      <div id="message" class="mt-2"></div>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const form = document.getElementById("md5-form");
    const input = document.getElementById("md5-input");
    const messageDiv = document.getElementById("message");

    form.addEventListener("submit", function (event) {
      event.preventDefault(); // 防止表单默认提交

      const md5Value = input.value.trim();

      if (!isValidMD5(md5Value)) {
        messageDiv.textContent = "请输入有效的 MD5 值。";
        messageDiv.className = "text-danger v2hls-text";
        return;
      }

      fetch(`http://127.0.0.1:8888/files/v2hls/${md5Value}`)
        .then((response) => response.json())
        .then((data) => {
          messageDiv.textContent = data.result;
          messageDiv.className = "text-success v2hls-text";
          checkTaskStatus(md5Value);
        })
        .catch((error) => {
          messageDiv.textContent = "请求失败，请稍后再试。";
          messageDiv.className = "text-danger v2hls-text";
        });
    });

    function isValidMD5(value) {
      const md5Regex = /^[a-fA-F0-9]{32}$/;
      return md5Regex.test(value);
    }

    function checkTaskStatus(md5Value) {
      const statusInterval = setInterval(() => {
        fetch(`http://127.0.0.1:8888/files/v2hls/status/${md5Value}`)
          .then((response) => response.json())
          .then((data) => {
            messageDiv.textContent = data.result;
            messageDiv.className =
              data.status === "完成" ? "text-success v2hls-text" : "text-warning v2hls-text";
            if (data.status === "完成" || data.status === "失败") {
              clearInterval(statusInterval);
            }
          })
          .catch((error) => {
            messageDiv.textContent = "状态查询失败。";
            messageDiv.className = "text-danger v2hls-text";
          });
      }, 5000); // 每5秒查询一次状态
    }
  });
</script>

f_proc/templates/f_proc/ct.html
{% extends "f_proc/base.html" %} 
{% block header %} 
  {% include 'f_proc/nav.html'%} 
{% endblock %} {% block content %} 
  {% include 'f_proc/base_ct.html' %}
{%endblock %}

f_proc/templates/f_proc/delete.html
{% extends "f_proc/base.html" %} 
{% block header %} 
  {% include 'f_proc/nav.html'%} 
{% endblock %} {% block content %} 
  {% include 'f_proc/base_delete.html' %}
{%endblock %}

f_proc/templates/f_proc/filter.html
{% extends "f_proc/base.html" %} 
{% block header %} 
  {% include 'f_proc/nav.html'%} 
{% endblock %} {% block content %} 
  {% include 'f_proc/base_filter.html' %}
{%endblock %}